<?php

namespace Source\Models\Permissions;

use Source\Core\Model;
use Source\Models\Widget;

/**
 *
 */
class UserPermission extends Model
{
    /**
     *
     */
    public function __construct()
    {
        parent::__construct("users_permissions", ["id"], ["users_id", "widgets_id", "can_view", "can_add", "can_edit", "can_delete"]);
    }

    /**
     * @param integer $users_id
     * @param integer $widgets_id
     * @param integer $can_view
     * @param integer $can_add
     * @param integer $can_edit
     * @param integer $can_delete
     * @return UserPermission
     */
    public function bootstrap(
        int $users_id,
        int $widgets_id,
        int $can_view,
        int $can_add,
        int $can_edit,
        int $can_delete

    ): UserPermission {
        $this->users_id = $users_id;
        $this->widgets_id = $widgets_id;
        $this->can_view = $can_view;
        $this->can_add = $can_add;
        $this->can_edit = $can_edit;
        $this->can_delete = $can_delete;
        return $this;
    }
    /**
     * @param integer $widgets_id
     * @param integer $users_id
     * @param string $columns
     * @return null|UserPermission
     */
    public function findByWidget(int $widgets_id,int $users_id, string $columns = "*"): ?UserPermission
    {
        $find = $this->find("widgets_id = :widgets_id, users_id= :users_id", "widgets_id={$widgets_id}&users_id={$users_id}", $columns);
        return $find->fetch();
    }


    /**
     * @param int $users_id
     * @param string $columns
     * @return UserPermission|mixed
     */
    public function findByUser(int $users_id, string $columns = "*")
    {
        $find = $this->find("users_id= :users_id", "users_id={$users_id}", $columns);
        return $find->fetch("true");
    }

    /**
     * @return bool
     */
    public function save(): bool
    {

        /** UserPermission Update */
        if (!empty($this->id)) {
            $userPermissionId = $this->id;

            if ($this->find("widgets_id = :w AND users_id = :u AND id != :i", "w={$this->widgets_id}&u={$this->users_id}&i={$userPermissionId}", "id")->fetch()) {
                $this->message->warning("As permissões do módulo já estão cadastradas");
                return false;
            }

            $this->update($this->safe(), "id = :id", "id={$userPermissionId}");
            if ($this->fail()) {
                $this->message->error("Erro ao atualizar, verifique os dados");
                return false;
            }
        }

        /** User Create */
        if (empty($this->id)) {
            if ($this->findByWidget($this->widgets_id, $this->users_id, "id")) {
                $this->message->warning("As permissões do módulo já estão cadastradas");
                return false;
            }

            $userPermissionId = $this->create($this->safe());
            if ($this->fail()) {
                $this->message->error("Erro ao cadastrar, verifique os dados");
                return false;
            }
        }

        $this->data = ($this->findById($userPermissionId))->data();
        return true;
    }

    /**
     * @param string $terms
     * @param string|null $params
     * @return bool
     */
    public function delete(string $terms, ?string $params): bool
    {
        return parent::delete($terms, $params); // TODO: Change the autogenerated stub
    }
}